baseURL: "https://aurelien-frick.githib.io" 
title: Aurelien Frick
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1 
        - name: Publications
          url: publications/
          weight: 2
        - name: CV
          url: cv/
          weight: 3
        - name: Diversity
          url: diversity/
          weight: 4
        - name: News
          url: news/
          weight: 5


params:
    description: "Welcome to my website! I'm a Leverhulme Early Career Research Fellow in the School of Psychology and Neuroscience at the University of St Andrews"
    author: Aurélien Frick
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","publications","cv","news"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Aurélien Frick
          subtitle: "Welcome to my website! I'm a Leverhulme Early Career Research Fellow at the University of St Andrews."
          imageUrl: "front_image.jpg"
          imageWidth: 120
          imageHeight: 150
          buttons:
            - name: About
              url: about/
            - name: Publications
              url: publications/
            - name: CV
              url: cv/
            - name: Diversity
              url: diversity/
            - name: News
              url: news/


    socialIcons:
        - name: CV
          url: CV_Aurelien_Frick.pdf
        - name: Email
          url: mailto:asaf1@st-andrews.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Ibkj76wAAAAJ&hl=en&oi=ao
        - name: LinkedIn
          url: https://www.linkedin.com/in/aurélien-frick-a11430399?miniProfileUrn=urn%3Ali%3Afsd_profile%3AACoAAGHF-K0BDVsskz9BdgUwI--0caFT2RyACvg&lipi=urn%3Ali%3Apage%3Ad_flagship3_detail_base%3B1pWkR6dTQm2JPjZP9xw0OQ%3D%3D
        - name: Bluesky
          url: https://bsky.app/profile/aurelfrick.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Aurélien Frick"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2